// Question bank — three formats:
//   type:'code'    → JS function problems with test cases (run in browser)
//   type:'numeric' → exact numerical answer with tolerance
//
// comparator options: 'exact' | 'sorted' (sort arrays before comparing) | 'any-palindrome'

const QUESTIONS = {
  tech: {
    easy: [
      {
        id: 'te1', type: 'code',
        title: 'Two Sum',
        description: 'Given an array of integers <code>nums</code> and an integer <code>target</code>, return the indices of the two numbers that add up to <code>target</code>.\n\nYou may assume each input has exactly one solution. You may not use the same element twice.',
        examples: [
          { input: 'nums = [2, 7, 11, 15], target = 9', output: '[0, 1]', explanation: 'nums[0] + nums[1] = 9' },
          { input: 'nums = [3, 2, 4], target = 6', output: '[1, 2]' },
        ],
        constraints: ['2 ≤ nums.length ≤ 10⁴', '-10⁹ ≤ nums[i] ≤ 10⁹', 'Only one valid answer exists'],
        starter: 'function twoSum(nums, target) {\n  \n}',
        pythonStarter: 'def two_sum(nums, target):\n    pass',
        functionName: 'twoSum',
        pythonFunctionName: 'two_sum',
        comparator: 'sorted',
        testCases: [
          { input: [[2,7,11,15], 9], expected: [0,1], label: 'nums=[2,7,11,15], target=9' },
          { input: [[3,2,4], 6], expected: [1,2], label: 'nums=[3,2,4], target=6' },
          { input: [[3,3], 6], expected: [0,1], label: 'nums=[3,3], target=6' },
        ],
        hiddenCases: [
          { input: [[-1,-2,-3,-4,-5], -8], expected: [2,4] },
          { input: [[1,5,3,2], 4], expected: [2,3] },
        ],
        explanation: 'Use a hash map to store each number\'s index. For each num, check if (target - num) is already in the map. This gives O(n) time, O(n) space — much better than the O(n²) brute force.',
      },
      {
        id: 'te2', type: 'code',
        title: 'Contains Duplicate',
        description: 'Given an integer array <code>nums</code>, return <code>true</code> if any value appears <strong>at least twice</strong>, and <code>false</code> if every element is distinct.',
        examples: [
          { input: 'nums = [1, 2, 3, 1]', output: 'true' },
          { input: 'nums = [1, 2, 3, 4]', output: 'false' },
          { input: 'nums = [1, 1, 1, 3, 3, 4, 3, 2, 4, 2]', output: 'true' },
        ],
        constraints: ['1 ≤ nums.length ≤ 10⁵', '-10⁹ ≤ nums[i] ≤ 10⁹'],
        starter: 'function containsDuplicate(nums) {\n  \n}',
        pythonStarter: 'def contains_duplicate(nums):\n    pass',
        functionName: 'containsDuplicate',
        pythonFunctionName: 'contains_duplicate',
        comparator: 'exact',
        testCases: [
          { input: [[1,2,3,1]], expected: true, label: '[1,2,3,1]' },
          { input: [[1,2,3,4]], expected: false, label: '[1,2,3,4]' },
          { input: [[1,1,1,3,3,4]], expected: true, label: '[1,1,1,3,3,4]' },
        ],
        hiddenCases: [
          { input: [[1]], expected: false },
          { input: [[1,2]], expected: false },
          { input: [[1,1]], expected: true },
        ],
        explanation: 'Add each number to a Set. If the number already exists in the Set, return true. If you finish the loop without finding one, return false. O(n) time, O(n) space.',
      },
      {
        id: 'te3', type: 'code',
        title: 'Palindrome Number',
        description: 'Given an integer <code>x</code>, return <code>true</code> if <code>x</code> is a <strong>palindrome</strong>, and <code>false</code> otherwise.\n\nA palindrome reads the same forwards and backwards.',
        examples: [
          { input: 'x = 121', output: 'true', explanation: '121 reads as 121 from left to right and from right to left.' },
          { input: 'x = -121', output: 'false', explanation: 'From left to right: -121. From right to left: 121-. Not a palindrome.' },
          { input: 'x = 10', output: 'false' },
        ],
        constraints: ['-2³¹ ≤ x ≤ 2³¹ - 1'],
        starter: 'function isPalindrome(x) {\n  \n}',
        pythonStarter: 'def is_palindrome(x):\n    pass',
        functionName: 'isPalindrome',
        pythonFunctionName: 'is_palindrome',
        comparator: 'exact',
        testCases: [
          { input: [121], expected: true, label: 'x = 121' },
          { input: [-121], expected: false, label: 'x = -121' },
          { input: [10], expected: false, label: 'x = 10' },
          { input: [0], expected: true, label: 'x = 0' },
        ],
        hiddenCases: [
          { input: [1001], expected: false },
          { input: [1221], expected: true },
        ],
        explanation: 'Negative numbers are never palindromes. Convert x to a string and compare it to its reverse: `String(x) === String(x).split("").reverse().join("")`. Or do it mathematically by reversing the digits.',
      },
    ],
    medium: [
      {
        id: 'tm1', type: 'code',
        title: 'Valid Parentheses',
        description: 'Given a string <code>s</code> containing only the characters <code>(</code>, <code>)</code>, <code>{</code>, <code>}</code>, <code>[</code> and <code>]</code>, determine if the input string is valid.\n\nAn input string is valid if:\n• Open brackets are closed by the same type of brackets\n• Open brackets are closed in the correct order\n• Every close bracket has a corresponding open bracket',
        examples: [
          { input: 's = "()"', output: 'true' },
          { input: 's = "()[]{}"', output: 'true' },
          { input: 's = "(]"', output: 'false' },
          { input: 's = "([)]"', output: 'false' },
          { input: 's = "{[]}"', output: 'true' },
        ],
        constraints: ['1 ≤ s.length ≤ 10⁴', 's consists of parentheses only ()[]{}'],
        starter: 'function isValid(s) {\n  \n}',
        pythonStarter: 'def is_valid(s):\n    pass',
        functionName: 'isValid',
        pythonFunctionName: 'is_valid',
        comparator: 'exact',
        testCases: [
          { input: ['()'], expected: true, label: '"()"' },
          { input: ['()[]{}'], expected: true, label: '"()[]{}"' },
          { input: ['(]'], expected: false, label: '"(]"' },
          { input: ['([)]'], expected: false, label: '"([)]"' },
          { input: ['{[]}'], expected: true, label: '"{[]}"' },
        ],
        hiddenCases: [
          { input: [''], expected: true },
          { input: ['{'], expected: false },
          { input: ['(((('], expected: false },
        ],
        explanation: 'Classic stack problem. Push open brackets onto a stack. When you see a close bracket, check if the top of the stack is the matching open bracket. If not (or stack is empty), return false. At the end, the stack should be empty.',
      },
      {
        id: 'tm2', type: 'code',
        title: 'Maximum Subarray',
        description: 'Given an integer array <code>nums</code>, find the subarray with the largest sum, and return its sum.\n\nA subarray is a contiguous non-empty sequence of elements within an array.',
        examples: [
          { input: 'nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]', output: '6', explanation: 'Subarray [4,-1,2,1] has the largest sum = 6.' },
          { input: 'nums = [1]', output: '1' },
          { input: 'nums = [5, 4, -1, 7, 8]', output: '23' },
        ],
        constraints: ['1 ≤ nums.length ≤ 10⁵', '-10⁴ ≤ nums[i] ≤ 10⁴'],
        starter: 'function maxSubArray(nums) {\n  \n}',
        pythonStarter: 'def max_sub_array(nums):\n    pass',
        functionName: 'maxSubArray',
        pythonFunctionName: 'max_sub_array',
        comparator: 'exact',
        testCases: [
          { input: [[-2,1,-3,4,-1,2,1,-5,4]], expected: 6, label: '[-2,1,-3,4,-1,2,1,-5,4]' },
          { input: [[1]], expected: 1, label: '[1]' },
          { input: [[5,4,-1,7,8]], expected: 23, label: '[5,4,-1,7,8]' },
          { input: [[-1]], expected: -1, label: '[-1]' },
        ],
        hiddenCases: [
          { input: [[-2,-1]], expected: -1 },
          { input: [[1,2,3,-4,5]], expected: 7 },
        ],
        explanation: "Kadane's Algorithm: keep a running `currentSum`. At each element, either extend the current subarray or start fresh (whichever is larger). Track the global max. O(n) time, O(1) space.",
      },
      {
        id: 'tm3', type: 'code',
        title: 'Climbing Stairs',
        description: 'You are climbing a staircase with <code>n</code> steps. Each time you can climb <strong>1 or 2 steps</strong>. In how many distinct ways can you climb to the top?',
        examples: [
          { input: 'n = 2', output: '2', explanation: '2 ways: {1,1} or {2}' },
          { input: 'n = 3', output: '3', explanation: '3 ways: {1,1,1}, {1,2}, {2,1}' },
        ],
        constraints: ['1 ≤ n ≤ 45'],
        starter: 'function climbStairs(n) {\n  \n}',
        pythonStarter: 'def climb_stairs(n):\n    pass',
        functionName: 'climbStairs',
        pythonFunctionName: 'climb_stairs',
        comparator: 'exact',
        testCases: [
          { input: [2], expected: 2, label: 'n = 2' },
          { input: [3], expected: 3, label: 'n = 3' },
          { input: [5], expected: 8, label: 'n = 5' },
          { input: [1], expected: 1, label: 'n = 1' },
        ],
        hiddenCases: [
          { input: [10], expected: 89 },
          { input: [44], expected: 1134903170 },
        ],
        explanation: 'This is Fibonacci in disguise. ways(n) = ways(n-1) + ways(n-2). Either you came from step n-1 (1 step) or n-2 (2 steps). Use DP with two variables to get O(n) time, O(1) space.',
      },
    ],
    hard: [
      {
        id: 'th1', type: 'code',
        title: 'Jump Game',
        description: 'You are given an integer array <code>nums</code>. You are initially positioned at the first index. Each element represents your maximum jump length at that position.\n\nReturn <code>true</code> if you can reach the last index, or <code>false</code> otherwise.',
        examples: [
          { input: 'nums = [2, 3, 1, 1, 4]', output: 'true', explanation: 'Jump 1 to index 1, then 3 steps to the last index.' },
          { input: 'nums = [3, 2, 1, 0, 4]', output: 'false', explanation: 'You will always arrive at index 3 with 0 steps remaining.' },
        ],
        constraints: ['1 ≤ nums.length ≤ 10⁴', '0 ≤ nums[i] ≤ 10⁵'],
        starter: 'function canJump(nums) {\n  \n}',
        pythonStarter: 'def can_jump(nums):\n    pass',
        functionName: 'canJump',
        pythonFunctionName: 'can_jump',
        comparator: 'exact',
        testCases: [
          { input: [[2,3,1,1,4]], expected: true, label: '[2,3,1,1,4]' },
          { input: [[3,2,1,0,4]], expected: false, label: '[3,2,1,0,4]' },
          { input: [[0]], expected: true, label: '[0] (already at end)' },
          { input: [[2,0,0]], expected: true, label: '[2,0,0]' },
        ],
        hiddenCases: [
          { input: [[1,0,0]], expected: false },
          { input: [[1,1,0,1]], expected: false },
          { input: [[3,0,0,0]], expected: true },
        ],
        explanation: 'Greedy: track the farthest index reachable so far. At each index i, if i > maxReach, you\'re stuck — return false. Otherwise update maxReach = max(maxReach, i + nums[i]). O(n) time, O(1) space.',
      },
      {
        id: 'th2', type: 'code',
        title: 'Coin Change',
        description: 'You are given an integer array <code>coins</code> representing coins of different denominations and an integer <code>amount</code>.\n\nReturn the <strong>fewest number of coins</strong> needed to make up that amount. If that amount cannot be made up, return <code>-1</code>.\n\nYou may use an unlimited number of each coin.',
        examples: [
          { input: 'coins = [1,5,10,25], amount = 36', output: '3', explanation: '25 + 10 + 1 = 36' },
          { input: 'coins = [2], amount = 3', output: '-1' },
          { input: 'coins = [1], amount = 0', output: '0' },
        ],
        constraints: ['1 ≤ coins.length ≤ 12', '1 ≤ coins[i] ≤ 2³¹ - 1', '0 ≤ amount ≤ 10⁴'],
        starter: 'function coinChange(coins, amount) {\n  \n}',
        pythonStarter: 'def coin_change(coins, amount):\n    pass',
        functionName: 'coinChange',
        pythonFunctionName: 'coin_change',
        comparator: 'exact',
        testCases: [
          { input: [[1,5,10,25], 36], expected: 3, label: 'coins=[1,5,10,25], amount=36' },
          { input: [[2], 3], expected: -1, label: 'coins=[2], amount=3' },
          { input: [[1], 0], expected: 0, label: 'amount=0' },
          { input: [[1,2,5], 11], expected: 3, label: 'coins=[1,2,5], amount=11' },
        ],
        hiddenCases: [
          { input: [[186,419,83,408], 6249], expected: 20 },
          { input: [[1], 10000], expected: 10000 },
        ],
        explanation: 'Bottom-up DP: create dp[0..amount] where dp[i] = min coins to make amount i. Initialize with Infinity, dp[0]=0. For each amount, try each coin: dp[i] = min(dp[i], dp[i-coin]+1). O(amount × coins) time.',
      },
      {
        id: 'th3', type: 'code',
        title: 'Unique Paths',
        description: 'A robot starts at the top-left corner of an <code>m × n</code> grid and tries to reach the bottom-right corner. The robot can only move <strong>right or down</strong>.\n\nReturn the number of possible unique paths.',
        examples: [
          { input: 'm = 3, n = 7', output: '28' },
          { input: 'm = 3, n = 2', output: '3', explanation: '↓↓→, ↓→↓, →↓↓' },
        ],
        constraints: ['1 ≤ m, n ≤ 100'],
        starter: 'function uniquePaths(m, n) {\n  \n}',
        pythonStarter: 'def unique_paths(m, n):\n    pass',
        functionName: 'uniquePaths',
        pythonFunctionName: 'unique_paths',
        comparator: 'exact',
        testCases: [
          { input: [3, 7], expected: 28, label: 'm=3, n=7' },
          { input: [3, 2], expected: 3, label: 'm=3, n=2' },
          { input: [1, 1], expected: 1, label: 'm=1, n=1' },
          { input: [2, 2], expected: 2, label: 'm=2, n=2' },
        ],
        hiddenCases: [
          { input: [7, 3], expected: 28 },
          { input: [100, 1], expected: 1 },
        ],
        explanation: 'DP: paths(i,j) = paths(i-1,j) + paths(i,j-1). Every cell is reachable from above or from the left. First row and column are all 1s (only one way to reach them). O(m×n) time. Can also be solved with combinatorics: C(m+n-2, m-1).',
      },
    ],
  },

  quant: {
    easy: [
      {
        id: 'qe4', type: 'numeric',
        title: 'At Least One Head',
        description: 'You flip a fair coin <strong>twice</strong>.\n\nWhat is the probability of getting <strong>at least one head</strong>?\n\nEnter as a decimal rounded to 2 decimal places (e.g. <code>0.75</code>).',
        unit: '',
        answer: 0.75,
        tolerance: 0.005,
        steps: [
          { label: 'P(no heads at all)', value: 'P(TT) = (1/2)² = 0.25' },
          { label: 'Complement rule', value: 'P(at least one head) = 1 − P(no heads)' },
          { label: 'Result', value: '1 − 0.25 = 0.75' },
        ],
        explanation: 'Use the complement: P(≥1 head) = 1 − P(TT) = 1 − (1/2)² = 1 − 0.25 = 0.75. The complement approach avoids summing cases (HT, TH, HH).',
      },
      {
        id: 'qe5', type: 'numeric',
        title: 'Matching Dice',
        description: 'You roll two fair 6-sided dice simultaneously.\n\nWhat is the probability that <strong>both dice show the same number</strong>?\n\nEnter as a decimal rounded to 4 places (e.g. <code>0.1667</code>).',
        unit: '',
        answer: 0.1667,
        tolerance: 0.0005,
        steps: [
          { label: 'Condition on the first die', value: 'It shows any value — that\'s fine' },
          { label: 'Second die must match', value: 'P(match) = 1/6 ≈ 0.1667' },
        ],
        explanation: 'Regardless of what the first die shows, the second must match it: P = 1/6 ≈ 0.1667. Equivalently: 6 matching pairs out of 36 total outcomes.',
      },
      {
        id: 'qe6', type: 'numeric',
        title: 'Simple Return',
        description: 'A stock price rises from <strong>$80</strong> to <strong>$100</strong> over one year.\n\nWhat is the <strong>simple return</strong>?\n\nEnter as a percentage (e.g. <code>25.00</code> for 25%).',
        unit: '%',
        answer: 25,
        tolerance: 0.05,
        steps: [
          { label: 'Price gain', value: '$100 − $80 = $20' },
          { label: 'Return = gain / initial price', value: '$20 ÷ $80 × 100% = 25%' },
        ],
        explanation: 'Simple return = (P_T − P_0) / P_0 = (100 − 80) / 80 = 0.25 = 25%.',
      },
      {
        id: 'qe1', type: 'numeric',
        title: 'Expected Value of a Dice Game',
        description: 'You roll a single fair 6-sided die. You win <strong>$4</strong> if you roll a 6, and you lose <strong>$1</strong> for any other result.\n\nWhat is the <strong>expected value</strong> of this game in dollars?\n\nEnter your answer rounded to 2 decimal places (e.g. <code>-0.50</code>).',
        unit: '$',
        answer: -0.17,
        tolerance: 0.015,
        steps: [
          { label: 'P(rolling 6)', value: '1/6 ≈ 0.1667' },
          { label: 'P(not rolling 6)', value: '5/6 ≈ 0.8333' },
          { label: 'EV', value: '(1/6)×$4 + (5/6)×(−$1) = $0.667 − $0.833 = −$0.167 ≈ −$0.17' },
        ],
        explanation: 'EV = Σ P(outcome) × value = (1/6)(4) + (5/6)(−1) = 4/6 − 5/6 = −1/6 ≈ −$0.17. The house has an edge — you lose on average.',
      },
      {
        id: 'qe2', type: 'numeric',
        title: 'Probability: Red Face Card',
        description: 'You draw one card at random from a standard 52-card deck.\n\nWhat is the probability of drawing a <strong>red face card</strong> (Jack, Queen, or King of Hearts or Diamonds)?\n\nEnter your answer as a decimal rounded to 4 places (e.g. <code>0.1154</code>).',
        unit: '',
        answer: 0.1154,
        tolerance: 0.0005,
        steps: [
          { label: 'Red face cards', value: 'J♥, Q♥, K♥, J♦, Q♦, K♦ = 6 cards' },
          { label: 'Total cards', value: '52' },
          { label: 'Probability', value: '6/52 = 3/26 ≈ 0.1154' },
        ],
        explanation: 'P = favorable outcomes / total outcomes = 6/52 = 3/26 ≈ 0.1154.',
      },
      {
        id: 'qe3', type: 'numeric',
        title: 'Portfolio Expected Return',
        description: 'A portfolio is <strong>70% stocks</strong> (expected return <strong>9%</strong>) and <strong>30% bonds</strong> (expected return <strong>3%</strong>).\n\nWhat is the portfolio\'s expected annual return?\n\nEnter your answer as a percentage (e.g. <code>6.50</code> for 6.50%).',
        unit: '%',
        answer: 7.2,
        tolerance: 0.05,
        steps: [
          { label: 'Stock contribution', value: '0.70 × 9% = 6.3%' },
          { label: 'Bond contribution', value: '0.30 × 3% = 0.9%' },
          { label: 'Total', value: '6.3% + 0.9% = 7.2%' },
        ],
        explanation: 'E[R] = w₁×r₁ + w₂×r₂ = 0.70×9% + 0.30×3% = 6.3% + 0.9% = 7.2%.',
      },
    ],
    medium: [
      {
        id: 'qm4', type: 'numeric',
        title: "Bayes' Theorem: Medical Test",
        description: 'A disease affects <strong>10%</strong> of a population.\n\nA diagnostic test has:\n• <strong>90% sensitivity</strong> (correctly detects disease)\n• <strong>80% specificity</strong> (correctly identifies healthy people)\n\nA patient tests positive. What is the probability they actually have the disease?\n\nEnter as a decimal rounded to 3 places (e.g. <code>0.333</code>).',
        unit: '',
        answer: 0.333,
        tolerance: 0.002,
        steps: [
          { label: 'P(positive | disease)', value: '90% sensitivity → 0.9' },
          { label: 'P(positive | healthy)', value: '1 − 80% specificity = 20% false positive rate → 0.2' },
          { label: 'P(positive overall)', value: '0.9×0.1 + 0.2×0.9 = 0.09 + 0.18 = 0.27' },
          { label: 'P(disease | positive)', value: '0.09 ÷ 0.27 = 1/3 ≈ 0.333' },
        ],
        explanation: "Bayes': P(D|+) = P(+|D)×P(D) / P(+) = 0.9×0.1 / 0.27 = 1/3 ≈ 0.333. Even with a 90% sensitive test, only 1 in 3 positives actually has the disease when prevalence is just 10%. This is why screening rare diseases needs very high specificity.",
      },
      {
        id: 'qm5', type: 'numeric',
        title: 'CAPM Expected Return',
        description: 'Using the <strong>Capital Asset Pricing Model (CAPM)</strong>:\n\n• Risk-free rate: <strong>3%</strong>\n• Expected market return: <strong>10%</strong>\n• Asset beta (β): <strong>1.5</strong>\n\nWhat is the <strong>expected return</strong> of the asset?\n\nEnter as a percentage (e.g. <code>13.50</code>).',
        unit: '%',
        answer: 13.5,
        tolerance: 0.05,
        steps: [
          { label: 'Market risk premium', value: 'E[Rm] − rf = 10% − 3% = 7%' },
          { label: 'Beta contribution', value: 'β × 7% = 1.5 × 7% = 10.5%' },
          { label: 'E[R] = rf + β × (E[Rm] − rf)', value: '3% + 10.5% = 13.5%' },
        ],
        explanation: 'CAPM: E[R] = rf + β(E[Rm]−rf) = 3% + 1.5×7% = 13.5%. A beta of 1.5 means 50% more market exposure than the average asset. The extra return comes from bearing extra systematic risk.',
      },
      {
        id: 'qm6', type: 'numeric',
        title: 'Standard Deviation of Returns',
        description: 'A stock has the following annual return distribution:\n• <strong>+20%</strong> with probability 0.5\n• <strong>−10%</strong> with probability 0.3\n• <strong>0%</strong> with probability 0.2\n\nWhat is the <strong>standard deviation</strong> of returns?\n\nEnter as a percentage rounded to 2 decimal places.',
        unit: '%',
        answer: 13.45,
        tolerance: 0.05,
        steps: [
          { label: 'E[R]', value: '0.5×20 + 0.3×(−10) + 0.2×0 = 10 − 3 = 7%' },
          { label: 'Variance = Σ pᵢ×(rᵢ−E[R])²', value: '0.5×(13)² + 0.3×(17)² + 0.2×(7)² = 84.5 + 86.7 + 9.8 = 181' },
          { label: 'σ = √Variance', value: '√181 ≈ 13.45%' },
        ],
        explanation: 'E[R] = 7%. Variance = Σpᵢ(rᵢ−μ)² = 0.5×169 + 0.3×289 + 0.2×49 = 84.5 + 86.7 + 9.8 = 181. σ = √181 ≈ 13.45%.',
      },
      {
        id: 'qm1', type: 'numeric',
        title: 'Returns Are Not Symmetric',
        description: 'A stock rises <strong>50%</strong> in January, then falls <strong>50%</strong> in February.\n\nStarting from $100, what is the stock price at the end of February?\n\nEnter the price in dollars (e.g. <code>75.00</code>).',
        unit: '$',
        answer: 75,
        tolerance: 0.01,
        steps: [
          { label: 'After +50%', value: '$100 × 1.50 = $150' },
          { label: 'After −50%', value: '$150 × 0.50 = $75' },
        ],
        explanation: 'Percentage gains and losses are NOT symmetric. A 50% gain followed by a 50% loss = $100 × 1.5 × 0.5 = $75. Net return = −25%. This is why geometric returns are used for multi-period analysis.',
      },
      {
        id: 'qm2', type: 'numeric',
        title: 'Monty Hall Problem',
        description: 'You\'re on a game show. There are <strong>3 doors</strong>: one has a car, two have goats. You pick Door 1. The host (who always knows where the car is) opens Door 3, revealing a goat.\n\nYou switch to Door 2. What is the probability you win the car?\n\nEnter as a fraction in decimal form (e.g. <code>0.333</code> for 1/3).',
        unit: '',
        answer: 0.6667,
        tolerance: 0.001,
        steps: [
          { label: 'P(car behind Door 1) initially', value: '1/3' },
          { label: 'P(car NOT behind Door 1)', value: '2/3 (split across Doors 2 and 3)' },
          { label: 'Host reveals a goat behind Door 3', value: 'Your original pick stays at 1/3 — the remaining 2/3 consolidates onto Door 2' },
          { label: 'P(win by switching)', value: '2/3 ≈ 0.6667' },
        ],
        explanation: 'Switching gives you 2/3 probability of winning. Your initial pick had a 1/3 chance. The remaining 2/3 probability was split between doors 2 and 3 — when the host eliminates one, all 2/3 collapses onto the remaining door. Always switch.',
      },
      {
        id: 'qm3', type: 'numeric',
        title: 'Geometric Distribution',
        description: 'You roll a fair 6-sided die repeatedly until you roll a <strong>6</strong>.\n\nWhat is the <strong>expected number of rolls</strong>?\n\nEnter an exact integer.',
        unit: 'rolls',
        answer: 6,
        tolerance: 0,
        steps: [
          { label: 'Distribution', value: 'Geometric with p = 1/6' },
          { label: 'E[X]', value: '1/p = 1/(1/6) = 6' },
        ],
        explanation: 'For a geometric distribution with success probability p, E[X] = 1/p. Here p = 1/6, so you expect to roll 6 times on average.',
      },
    ],
    hard: [
      {
        id: 'qh4', type: 'numeric',
        title: 'Risk-Neutral Probability',
        description: 'In a one-period <strong>binomial options model</strong>:\n• Current stock price: <strong>$100</strong>\n• Up move to: <strong>$110</strong>\n• Down move to: <strong>$90</strong>\n• Risk-free rate: <strong>5%</strong> per period\n\nWhat is the <strong>risk-neutral probability</strong> of an up move?\n\nEnter as a decimal rounded to 4 places (e.g. <code>0.7500</code>).',
        unit: '',
        answer: 0.75,
        tolerance: 0.005,
        steps: [
          { label: 'Risk-neutral condition', value: 'p×S_u + (1−p)×S_d = S×(1+r)' },
          { label: 'Substituting values', value: 'p×110 + (1−p)×90 = 100×1.05 = 105' },
          { label: 'Simplify', value: '90 + 20p = 105 → 20p = 15 → p = 0.75' },
        ],
        explanation: 'The risk-neutral probability satisfies: p = (S(1+r) − S_d) / (S_u − S_d) = (105−90)/(110−90) = 15/20 = 0.75. Note: this is NOT the real probability of an up move — it\'s a mathematical construct used to price derivatives by discounting at the risk-free rate.',
      },
      {
        id: 'qh5', type: 'numeric',
        title: 'Continuously Compounded Return',
        description: 'A stock price doubles from <strong>$50</strong> to <strong>$100</strong> in exactly one year.\n\nWhat is the <strong>continuously compounded (log) return</strong>?\n\nUse ln(2) ≈ 0.6931. Enter as a percentage rounded to 2 decimal places.',
        unit: '%',
        answer: 69.31,
        tolerance: 0.1,
        steps: [
          { label: 'Log return formula', value: 'r_c = ln(P_T / P_0) = ln(100/50)' },
          { label: 'Evaluate', value: '= ln(2) ≈ 0.6931 = 69.31%' },
        ],
        explanation: 'Continuously compounded return = ln(P_T/P_0) = ln(2) ≈ 69.31%. Compare to the simple return of 100%. Log returns are additive over time and normally distributed under GBM, making them essential in quantitative finance.',
      },
      {
        id: 'qh6', type: 'numeric',
        title: 'Sharpe Ratio Comparison',
        description: 'Two portfolios, risk-free rate = 2%:\n\n• Portfolio A: expected return <strong>15%</strong>, volatility <strong>18%</strong>\n• Portfolio B: expected return <strong>9%</strong>, volatility <strong>6%</strong>\n\nWhat is <strong>Portfolio B\'s Sharpe ratio</strong>? Round to 2 decimal places.',
        unit: '',
        answer: 1.17,
        tolerance: 0.01,
        steps: [
          { label: "Portfolio B excess return", value: '9% − 2% = 7%' },
          { label: 'Sharpe(B) = excess return ÷ σ', value: '7% ÷ 6% ≈ 1.17' },
        ],
        explanation: 'Sharpe(B) = (9%−2%)/6% = 1.17. Sharpe(A) = (15%−2%)/18% = 0.72. Despite lower absolute return, B is more efficient per unit of risk — a critical insight for risk-adjusted portfolio evaluation.',
      },
      {
        id: 'qh1', type: 'numeric',
        title: 'Portfolio Volatility',
        description: 'A portfolio: <strong>60% stocks</strong> (σ = 20%) and <strong>40% bonds</strong> (σ = 5%).\nThe correlation between them is <strong>zero</strong>.\n\nWhat is the portfolio standard deviation (σ)?\n\nEnter as a percentage rounded to 2 decimal places (e.g. <code>12.17</code>).',
        unit: '%',
        answer: 12.17,
        tolerance: 0.05,
        steps: [
          { label: 'Variance formula (ρ=0)', value: 'Var = w₁²σ₁² + w₂²σ₂²' },
          { label: 'Substitute', value: 'Var = (0.6)²(0.20)² + (0.4)²(0.05)²' },
          { label: 'Calculate', value: '= 0.36×0.04 + 0.16×0.0025 = 0.0144 + 0.0004 = 0.0148' },
          { label: 'σ', value: '√0.0148 ≈ 0.1217 = 12.17%' },
        ],
        explanation: 'With zero correlation, portfolio variance = w₁²σ₁² + w₂²σ₂². Cross terms drop out. Diversification reduces portfolio volatility below the weighted average (which would be 14%).',
      },
      {
        id: 'qh2', type: 'numeric',
        title: 'Expected Value: Roll Until 6',
        description: 'You roll a fair die until you see a 6. Your payout is <strong>$2ⁿ</strong> where n is the total number of rolls.\n\nWhat is the <strong>expected payout</strong>?\n\nHint: This is a famous paradox. Enter your answer (integer or "inf" not accepted — compute the finite closed form for finite n).\n\nFor n capped at 20 rolls max, what is the expected payout in dollars? Round to nearest dollar.',
        unit: '$',
        answer: 21,
        tolerance: 1,
        steps: [
          { label: 'P(stop at roll n)', value: '(5/6)^(n-1) × (1/6)' },
          { label: 'Payout at roll n', value: '2ⁿ' },
          { label: 'EV (capped at 20)', value: 'Σ(n=1 to 20) (5/6)^(n-1)×(1/6)×2ⁿ ≈ $21' },
        ],
        explanation: 'Each term: (1/6)×(5/6)^(n-1)×2ⁿ = (1/6)(10/6)^(n-1)×2 → each term ≈ (5/3)^(n-1)/3. Sum of first 20 terms ≈ $21. The uncapped version diverges (St. Petersburg paradox).',
      },
      {
        id: 'qh3', type: 'numeric',
        title: 'Options Delta Hedging P&L',
        description: 'You hold a delta-neutral portfolio: <strong>long 100 call options</strong> (delta = 0.5 each), <strong>short 50 shares</strong>.\n\nThe stock moves from <strong>$100 to $105</strong> (a +5% move).\n\nApproximately, what is your P&L from this position in dollars? (Use delta approximation only — ignore gamma.)',
        unit: '$',
        answer: 0,
        tolerance: 5,
        steps: [
          { label: 'Call P&L', value: '100 options × 0.5 delta × $5 move = +$250' },
          { label: 'Stock P&L', value: '−50 shares × $5 move = −$250' },
          { label: 'Net P&L', value: '$250 − $250 = $0 (delta neutral)' },
        ],
        explanation: 'Delta-neutral means the portfolio is hedged against small moves. Long calls gain as stock rises, but short stock position loses by the same amount. Net P&L ≈ $0 (delta approximation). In reality, gamma creates positive convexity that generates small profit.',
      },
    ],
  },

  ib: {
    easy: [
      {
        id: 'ibe1', type: 'numeric',
        title: 'Equity Value Bridge',
        description: 'A company has:\n• EBITDA of <strong>$100M</strong>\n• Trades at <strong>8.0x EV/EBITDA</strong>\n• <strong>$300M</strong> in total debt\n• <strong>$50M</strong> in cash\n\nWhat is the <strong>equity value</strong> in millions of dollars?',
        unit: '$M',
        answer: 550,
        tolerance: 1,
        steps: [
          { label: 'Enterprise Value', value: '$100M × 8.0x = $800M' },
          { label: 'Net Debt', value: '$300M debt − $50M cash = $250M' },
          { label: 'Equity Value', value: 'EV − Net Debt = $800M − $250M = $550M' },
        ],
        explanation: 'Equity Value = EV − Net Debt. EV = EBITDA × multiple = $800M. Net Debt = Debt − Cash = $250M. Equity Value = $550M.',
      },
      {
        id: 'ibe2', type: 'numeric',
        title: 'Year 1 Interest Expense',
        description: 'A private equity firm acquires a company for <strong>$500M enterprise value</strong>.\n\nThe deal is financed with <strong>60% debt</strong> at an interest rate of <strong>8%</strong>.\n\nWhat is the Year 1 interest expense in millions of dollars?',
        unit: '$M',
        answer: 24,
        tolerance: 0.1,
        steps: [
          { label: 'Debt amount', value: '60% × $500M = $300M' },
          { label: 'Interest expense', value: '$300M × 8% = $24M' },
        ],
        explanation: 'Debt = 60% × $500M = $300M. Interest = $300M × 8% = $24M per year.',
      },
      {
        id: 'ibe3', type: 'numeric',
        title: 'Operating Cash Flow',
        description: 'A company reports:\n• Net Income: <strong>$80M</strong>\n• Depreciation & Amortization: <strong>$20M</strong>\n• Increase in Working Capital: <strong>$10M</strong>\n• Capital Expenditures: <strong>$15M</strong>\n\nWhat is <strong>Free Cash Flow</strong> in millions of dollars?',
        unit: '$M',
        answer: 75,
        tolerance: 0.5,
        steps: [
          { label: 'Start with Net Income', value: '$80M' },
          { label: '+ D&A (non-cash)', value: '+$20M' },
          { label: '− Increase in Working Capital', value: '−$10M (cash used)' },
          { label: '− Capex', value: '−$15M' },
          { label: 'Free Cash Flow', value: '$80M + $20M − $10M − $15M = $75M' },
        ],
        explanation: 'FCF = Net Income + D&A − ΔWorking Capital − Capex. D&A is added back (non-cash charge). Working capital increase uses cash. Capex is an investment outflow.',
      },
    ],
    medium: [
      {
        id: 'ibm1', type: 'numeric',
        title: 'WACC Calculation',
        description: 'Calculate the Weighted Average Cost of Capital (WACC):\n\n• Capital structure: <strong>40% equity</strong>, <strong>60% debt</strong>\n• Cost of equity: <strong>12%</strong>\n• Pre-tax cost of debt: <strong>6%</strong>\n• Tax rate: <strong>30%</strong>\n\nEnter WACC as a percentage (e.g. <code>8.52</code>).',
        unit: '%',
        answer: 7.32,
        tolerance: 0.05,
        steps: [
          { label: 'Cost of Equity component', value: '40% × 12% = 4.80%' },
          { label: 'After-tax Cost of Debt', value: '6% × (1 − 30%) = 4.20%' },
          { label: 'Debt component', value: '60% × 4.20% = 2.52%' },
          { label: 'WACC', value: '4.80% + 2.52% = 7.32%' },
        ],
        explanation: 'WACC = Ke×(E/V) + Kd×(1−t)×(D/V). Debt has a tax shield because interest is deductible. The after-tax cost of debt = 6%×(1−0.30) = 4.2%. WACC = 0.40×12% + 0.60×4.2% = 7.32%.',
      },
      {
        id: 'ibm2', type: 'numeric',
        title: 'Cash Conversion Cycle',
        description: 'Calculate the Cash Conversion Cycle (CCC):\n\n• Days Sales Outstanding (DSO): <strong>45 days</strong>\n• Days Inventory Outstanding (DIO): <strong>60 days</strong>\n• Days Payable Outstanding (DPO): <strong>30 days</strong>\n\nWhat is the CCC in days?',
        unit: 'days',
        answer: 75,
        tolerance: 0,
        steps: [
          { label: 'Formula', value: 'CCC = DSO + DIO − DPO' },
          { label: 'Substitute', value: '45 + 60 − 30 = 75 days' },
        ],
        explanation: 'CCC = DSO + DIO − DPO = 45 + 60 − 30 = 75 days. This means the company has cash tied up in operations for 75 days. Lower CCC = more efficient working capital management.',
      },
      {
        id: 'ibm3', type: 'numeric',
        title: 'LBO Equity Return (MOIC)',
        description: 'A PE firm:\n• Buys a company for <strong>$1,000M</strong> EV at entry\n• Uses <strong>60% debt</strong> ($600M), <strong>40% equity</strong> ($400M)\n• Grows EBITDA from $100M to <strong>$150M</strong> over 5 years\n• Exits at the same <strong>10x EV/EBITDA</strong> multiple\n• Assume all debt is repaid by exit\n\nWhat is the <strong>Money-on-Money Multiple (MOIC)</strong>? Enter to 2 decimal places.',
        unit: 'x',
        answer: 3.75,
        tolerance: 0.05,
        steps: [
          { label: 'Exit EV', value: '$150M × 10x = $1,500M' },
          { label: 'Exit Equity (debt repaid)', value: '$1,500M − $0 = $1,500M' },
          { label: 'MOIC', value: '$1,500M ÷ $400M = 3.75x' },
        ],
        explanation: 'Exit EV = $150M × 10x = $1,500M. With all debt repaid, exit equity = $1,500M. MOIC = $1,500M / $400M entry equity = 3.75x. This drives ~30% IRR over 5 years.',
      },
    ],
    hard: [
      {
        id: 'ibh1', type: 'numeric',
        title: 'DCF Terminal Value',
        description: 'You are building a DCF model:\n• Year 5 Free Cash Flow: <strong>$50M</strong>\n• Terminal growth rate: <strong>3%</strong>\n• WACC: <strong>9%</strong>\n\nUsing the <strong>Gordon Growth Model</strong>, what is the terminal value (at end of Year 5) in millions of dollars?\n\nRound to 1 decimal place.',
        unit: '$M',
        answer: 858.3,
        tolerance: 1,
        steps: [
          { label: 'Formula', value: 'TV = FCF₅ × (1+g) / (WACC − g)' },
          { label: 'Numerator', value: '$50M × 1.03 = $51.5M' },
          { label: 'Denominator', value: '9% − 3% = 6%' },
          { label: 'Terminal Value', value: '$51.5M / 0.06 = $858.3M' },
        ],
        explanation: 'TV = FCF₅ × (1+g) / (WACC−g) = $50M × 1.03 / 0.06 = $51.5M / 0.06 = $858.3M. TV typically represents 60–80% of DCF value — the terminal growth rate assumption is therefore critical.',
      },
      {
        id: 'ibh2', type: 'numeric',
        title: 'Levered Beta',
        description: 'Re-lever a comparable company\'s beta to your target:\n\n• Unlevered beta (βᵤ) of comparable: <strong>0.90</strong>\n• Your target company: D/E ratio = <strong>0.75</strong>, tax rate = <strong>25%</strong>\n\nWhat is the <strong>levered beta (βₗ)</strong>? Round to 2 decimal places.',
        unit: '',
        answer: 1.41,
        tolerance: 0.02,
        steps: [
          { label: 'Formula', value: 'βₗ = βᵤ × [1 + (1−t) × D/E]' },
          { label: 'Substitute', value: 'βₗ = 0.90 × [1 + (1−0.25) × 0.75]' },
          { label: 'Bracket', value: '[1 + 0.75 × 0.75] = [1 + 0.5625] = 1.5625' },
          { label: 'βₗ', value: '0.90 × 1.5625 = 1.41' },
        ],
        explanation: 'Hamada equation: βₗ = βᵤ × [1 + (1−t) × D/E]. Leverage amplifies equity risk. An unlevered beta of 0.90 becomes 1.41 with 75% debt-to-equity — more financial risk means more equity volatility relative to the market.',
      },
      {
        id: 'ibh3', type: 'numeric',
        title: 'Accretion/Dilution: EPS Impact',
        description: 'Acquirer details:\n• Net Income: <strong>$200M</strong>, shares outstanding: <strong>100M</strong>\n• Acquirer EPS: $2.00, stock price: $40 (P/E = 20x)\n\nTarget details:\n• Purchase price: <strong>$500M</strong>, all-stock deal\n• Target Net Income: <strong>$30M</strong>\n• Assume no synergies\n\nWhat is the acquirer\'s <strong>new EPS</strong> post-acquisition? Round to 2 decimal places.',
        unit: '$',
        answer: 2.04,
        tolerance: 0.02,
        steps: [
          { label: 'New shares issued', value: '$500M ÷ $40/share = 12.5M shares' },
          { label: 'Total shares post-deal', value: '100M + 12.5M = 112.5M shares' },
          { label: 'Combined Net Income', value: '$200M + $30M = $230M' },
          { label: 'New EPS', value: '$230M ÷ 112.5M ≈ $2.04' },
        ],
        explanation: 'New shares = $500M / $40 = 12.5M. Total = 112.5M. Combined NI = $230M. New EPS = $230/112.5 ≈ $2.04. The deal is accretive (+$0.04/share) because the acquirer P/E (20x) exceeds the implied acquisition P/E ($500M / $30M NI ≈ 16.7x). Accretion occurs when acquirer P/E > deal P/E.',
      },
    ],
  },
};

function getRandomQuestion(category, difficulty) {
  const pool = QUESTIONS[category]?.[difficulty];
  if (!pool?.length) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}

function getRandomQuestions(category, difficulty, n) {
  const pool = (QUESTIONS[category]?.[difficulty] || []).slice();
  const result = [];
  while (result.length < n && pool.length > 0) {
    const i = Math.floor(Math.random() * pool.length);
    result.push(pool.splice(i, 1)[0]);
  }
  return result;
}

module.exports = { QUESTIONS, getRandomQuestion, getRandomQuestions };
